### ISSUE TITLE
White

### ISSUE THREAD

**Issue by t-hug** [Nun-z/XboxRetailModeAppGuideLegacy#3]
How do i get whitelisted for your apps?

**Comment by Nun-z** [comment]
Hi, thank you for your interest.  I created this guide to help others set up their own storefronts.  I generally don't distribute my apps to others.  You may want to contact others that have set up their own websites and ask them for access.

**Comment by t-hug** [comment]
So how come you have your apps on your website, i could of sworn i seen you allow access via a donation. If i am wrong then i do apologize but i really would like to try your apps listed. Thanks.

**Comment by Nun-z** [comment]
I do not accept donations and have never accepted donations.  Once in a while I will give someone access to test the apps.  Right now I don't need any more testers, but if that changes I can add you to the list.  My website is just for my own personal use, as I have an Xbox, with the exception of a couple of testers.

**Comment by t-hug** [comment]
Ok i perfectly understand, thanks for the heads up.
